apiVersion: v1
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true 
    server.basePath: "/kibana"
    server.rewriteBasePath: true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config-kibana