apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pv
  labels:
    component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: "standard"
  resources:
    requests:
      storage: 2Gi