apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app1
  name: app1
spec:
  containers:
  - image: quay.io/myafk/interactive:stable
    command: ["interactive", "config", "-t=fourth"]
    name: app1
    volumeMounts:
    - name: mnt
      mountPath: "/mnt"
      readOnly: true
    resources: {}
    env:
      - name: GRIDU_SECRET_ENV
        valueFrom:
          secretKeyRef:
            name: my-pass
            key: GRIDU_SECRET_ENV
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: mnt
    secret:
      secretName: my-pass
status: {}
