apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app1
  name: app1
spec:
  containers:
  - image: quay.io/myafk/interactive:stable
    command: ["interactive", "config", "-t=second"]
    name: app1
    volumeMounts:
      - name: my-cm-vol
        mountPath: /mnt/
    resources: {}
    env:
      - name: GRIDU_CONFIGMAP_ENV
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: GRIDU_CONFIGMAP_ENV
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: my-cm-vol
      configMap:
        name: my-config
status: {}
