apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: pod-app1
        image: quay.io/myafk/interactive:stable
        command: ["interactive", "workloads", "-t=second"]
        env:
        - name: FIRST_RUN_HASH
          value: 0208c0615d7aff81fafc87c7499330215d5f8a4d