---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    protocol: TCP
    name: http
  selector:
    app: es01